### ISSUE TITLE
missing parse_args & create_logger

### ISSUE THREAD

**Issue by YangChangHee** [XingliangJin/MCM-LDM#1]
hello, thank you for your great works!

I could`t find `parse_args, create_logger` code in demo.py & train.py

"""
from mld.config import parse_args
from mld.utils.logger import create_logger
"""

please check this.

best regard.

**Comment by XingliangJin** [comment]
Sorry for the missing files. I have unpload them. Please let me know if there is any other mistakes. Thanks!

**Comment by YangChangHee** [comment]
Thank you for your quick response!

Is there a way to get HumanML3D data at once? 

The preprocessing operation is too long. :(

**Comment by XingliangJin** [comment]
Due to the restrictions of the HumanML3D license, I am afraid I can‘t directly provide you with the dataset.
