### ISSUE TITLE
Evaluation metrics for FMD, CRA and SRA

### ISSUE THREAD

**Issue by daijucug** [XingliangJin/MCM-LDM#10]
Thank you for your excellent paper w/ the code!
I want to reproduce the evaluation for my further research. While waiting for your release of the quantitative evaluation code, I made ST-GCN-based content/style classifiers by modifying the discriminator of Diverse Motion Stylization. However, the accuracies of FMD, CRA, and SRA are different from those in your paper.

Could you provide the evaluation code and model for FMD, CRA, and SRA metrics?

**Comment by XingliangJin** [comment]
Thank you for your interest in our work! Due to the increasing demand for evaluation code, we will speed up the process and plan to release the first version of the evaluation code within this week.

**Comment by XingliangJin** [comment]
We have just initially open-sourced the evaluation code in [here.](https://github.com/XingliangJin/Eval_MCM-LDM) You are welcome to give it a try!
