### ISSUE TITLE
Evaluation question

### ISSUE THREAD

**Issue by codeozzz** [XingliangJin/MCM-LDM#11]
I'm really impressed with the work presented in your paper. I've been trying to replicate the evaluation process for my own research, but I'm having difficulty finding the exact metrics used. Would you be so kind as to share the methodology or metrics you employed for assessment? I would greatly appreciate your assistance in this matter.

**Comment by XingliangJin** [comment]
We have just initially open-sourced the evaluation code in [here.](https://github.com/XingliangJin/Eval_MCM-LDM) You are welcome to give it a try!
