### ISSUE TITLE
Style Motion File Generation

### ISSUE THREAD

**Issue by meongeun** [XingliangJin/MCM-LDM#13]
I have a question regarding the generation of style_motion files.

I would like to test using a different style_motion than the one provided. While I noticed the BaseModel.save_npy() function in your code, I am unsure how to utilize it for this purpose. Could you explain the steps or process you followed to extract the style_motion.npy file from the dataset?

Your guidance would be greatly appreciated.

**Comment by XingliangJin** [comment]
The style motion files use the 263-features format data from HumanML3D. You can either select motions from new_joint_vecs in HumanML3D as style motions or use your own SMPL-format motions and process them with HumanML3D's processing code to obtain 263-features format motion data.
