### ISSUE TITLE
evaluation metrics question

### ISSUE THREAD

**Issue by upyuyang** [XingliangJin/MCM-LDM#14]
Thank you for your work!
    I used the ./MCM-LDM/checkpoints/denoiser_checkpoint/denoiser.ckpt provided by you to run demo_transfer_crafmd.py and demo_transfer_sra.py. And then I obtained the pkl files. But my results is different from those in your paper when I use these pkl files in Eval_MCM-LDM. Can you give me some advices?

**Comment by XingliangJin** [comment]
This is due to the lack of a fixed seed during testing, which causes slight variations in the results each time. We have saved the pkl file used for evaluation in Eval_MCM-LDM. If you use this file for evaluation, the results will match those reported in the paper.

**Comment by upyuyang** [comment]
But my results are quite different from those in the paper. The CRA is 23.75 ,the SRA is 22.11 and the FMD is 413.84. And in the paper, the CRA is 35.75 ,the SRA is 58.00 and the FMD is 27.69. I wonder if the seed has such a big impact or if I'm doing the wrong step.
Thanks you very much!

**Comment by XingliangJin** [comment]
This is not a normal results. Can you provide more details of how you run the model? Have you change any config? 
---- Replied Message ----
***@***.***>Date12/05/2024 17:25 ***@***.***> CcXingliang ***@***.***>,
***@***.***>SubjectRe: [XingliangJin/MCM-LDM] evaluation metrics question (Issue #14)
But my results are quite different from those in the paper. The CRA is 23.75 ,the SRA is 22.11 and the FMD is 413.84. And in the paper, the CRA is 35.75 ,the SRA is 58.00 and the FMD is 27.69. I wonder if the seed has such a big impact or if I'm doing the wrong step.
Thanks you very much!

**Comment by upyuyang** [comment]
Sorry to bother you right now.I just repeated my experiment and I now have a few doubts that could be the cause of the not normal results. And the&nbsp;Details are as follows：


First, I change the dataset path in assets.yaml:



Second, I want to know if the version of numpy will effect the results? When I run the code:&nbsp;demo_transfer_crafmd.py and has the problems:








So I use “float” instead of "np.float"


And I change the version of numpy to 1.23.0


Third, I want to know the directory structure of “deps”. I don't use "bash prepare/download_smpl_models.sh" and "bash prepare/download_t2m_evaluators.sh".
Instead, I open the sh files, download these dependences in my browser, and put them in the directory "./deps" and unpack them. My structure is follows:



But it has error about:



So I copy ./deps/motionclip to ./deps/smpl as follows， it's true or false?





After them, I run:"python demo_transfer_crafmd.py --cfg ./configs/config_mld_humanml3d.yaml --cfg_assets ./configs/assets.yaml --style_motion_dir demo/content_test_feats --content_motion_dir demo/content_test_feats --scale 2.5"
                 "python demo_transfer_sra.py --cfg ./configs/config_mld_humanml3d.yaml --cfg_assets ./configs/assets.yaml --style_motion_dir demo/style_test_feats --content_motion_dir demo/style_test_feats --scale 2.5"


and copy the pkl files to Eval_MCM-LDM, and run: eval_FMD_CRA.py and eval_SRA.py to get the results.


But the results is also not normal.


I want to know if the step above is correct.


I greatly appreciate your help in answering my questions.
Thank you so much!







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XingliangJin/MCM-LDM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月5日(星期四) 下午5:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XingliangJin/MCM-LDM] evaluation metrics question (Issue #14)





 This is not a normal results. Can you provide more details of how you run the model? Have you change any config? 
 ---- Replied Message ----
 ***@***.***&gt;Date12/05/2024 17:25 ***@***.***&gt; CcXingliang ***@***.***&gt;,
 ***@***.***&gt;SubjectRe: [XingliangJin/MCM-LDM] evaluation metrics question (Issue #14)
 But my results are quite different from those in the paper. The CRA is 23.75 ,the SRA is 22.11 and the FMD is 413.84. And in the paper, the CRA is 35.75 ,the SRA is 58.00 and the FMD is 27.69. I wonder if the seed has such a big impact or if I'm doing the wrong step.
 Thanks you very much!

**Comment by XingliangJin** [comment]
Seems these steps can not cause the abnormal results. I will now repeat the evaluation process to see if anything goes wrong.

**Comment by XingliangJin** [comment]
There are two things I want you to confirm:
1. Is the demo results (visulized results) looks good?
2. Have you try the provided pkl file in Eval_MCM-LDM, and check the results is right or not.

**Comment by upyuyang** [comment]
1. I get the .gif files， and it looks good, eg:
2. I had try the provided pkl file, and the results is right.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xingliang ***@***.***&gt;; 
发送时间: 2024年12月5日(星期四) 晚上8:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XingliangJin/MCM-LDM] evaluation metrics question (Issue #14)














 
There are two things I want you to confirm:
  
Is the demo results (visulized results) looks good?
 
Have you try the provided pkl file in Eval_MCM-LDM, and check the results is right or not.

**Comment by XingliangJin** [comment]
My WeChat is 18296342338. It is better to comunicate in WeChat. : )
