### ISSUE TITLE
Where is the location of the feature extraction file

### ISSUE THREAD

**Issue by mengW6** [XingliangJin/MCM-LDM#4]
hello, thank you for your great works!
May I know which file contains the operations related to style extraction and trajectory feature extraction?

**Comment by XingliangJin** [comment]
Hi, the training and inference processes are mainly in [mld/models/modeltype/mld.py](https://github.com/XingliangJin/MCM-LDM/blob/main/mld/models/modeltype/mld.py). The denoiser network is in [mld/models/architectures/mld_denoiser.py](https://github.com/XingliangJin/MCM-LDM/blob/main/mld/models/architectures/mld_denoiser.py).

More specifically, code related to style extraction is [here](https://github.com/XingliangJin/MCM-LDM/blob/8724ee36d4b23ccbbcffac6151a11467d883480a/mld/models/modeltype/mld.py#L271), where we use the pretrained MotionCLIP to encode style motion. Code related to trajectory feature extraction is [here](https://github.com/XingliangJin/MCM-LDM/blob/8724ee36d4b23ccbbcffac6151a11467d883480a/mld/models/architectures/mld_denoiser.py#L248), where we use a transformer-based network to encode trajectory.

If you have any other questions, feel free to ask. :)

**Comment by mengW6** [comment]
Thank you for your reply :)
