### ISSUE TITLE
Any style

### ISSUE THREAD

**Issue by julkaztwittera** [XingliangJin/MCM-LDM#6]
Hi,
great work!
I wonder if MCM-LDM is able to generate any style, even the one that wasn't in the training set.

**Comment by XingliangJin** [comment]
Thank you for asking.

First, our method does not generate style. We transfer the style of an input style motion to another input content motion.

Second, after training on the HumanML3D dataset, our method can transfer motion styles that do not exist in the training set (for example, the style extracted from the motion reconstructed by the pose estimation method)
