### ISSUE TITLE
What are the input formats for the three conditions of the denoising module？

### ISSUE THREAD

**Issue by mengW6** [XingliangJin/MCM-LDM#7]
Hello, this is a very good job. I have a question that I hope to receive your answer to.What are the input formats for the three conditions (content, style, trajectory) of the denoising module？Is it entered in text format?
<img width="276" alt="图片2" src="https://github.com/user-attachments/assets/0cc0a2c4-3ce1-4fdc-8fde-7dfa9b83502f">

**Comment by XingliangJin** [comment]
Thank you for asking. 

The input format of these three conditions are encoded features (content: (bs, 6, 256), style: (bs, 1, 256), trajectory: (bs, 1, 256)) from content motion and style motion. We use this diagram to represent the main information contained in these features. We apologize for the misunderstandings. 

Please feel free to ask if you have any other questions.

**Comment by mengW6** [comment]
Thank you for your reply！If the content is replaced with a dance sequence and the style is changed to various dance styles such as ethnic dance, hip-hop, etc., does it meet the input requirements of the denoising module？

**Comment by XingliangJin** [comment]
I haven't done similar experiments on dance motions. I think you can try some examples : )
