### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by CH4N9ZY** [XingliangJin/MCM-LDM#8]
How to evaluate the model? I didn't see the evaluation code.
Thanks!

**Comment by XingliangJin** [comment]
Thank you for your interest and patience. I sincerely apologize for the delay in providing the evaluation code, as I have been occupied with other projects. In the meantime, we encourage you to evaluate this project using existing evaluation code from similar methods, such as [SMooDi](https://github.com/neu-vi/SMooDi), etc. I will prioritize organizing our code and notify you as soon as it is ready.

**Comment by XingliangJin** [comment]
We have just initially open-sourced the evaluation code in [here.](https://github.com/XingliangJin/Eval_MCM-LDM) You are welcome to give it a try!
